### ISSUE TITLE
Multi-allelic sites annotation

### ISSUE THREAD

**Issue by alohasiqi** [zhouhufeng/FAVORannotator#1]
Hello,

I just realized FAVOR cant handle multi-allelic sites, and it discards those sites for annotation. Is there any way to deal with this? Thanks!

**Comment by zhouhufeng** [comment]
Thanks very much for using FAVORannotator. 

It is important to note that like many standalone annotation software, performing functional annotation based on the exact match of chromosome-position-refAllele-altAllele, therefore, with multi-allelic sites it is not properly formatted inputted formats. 

I am so glad to know the issue of not matched annotation is caused by the multi-allelic sites. Actually  the FAVORannotator database can help with the multi-allelic sites of your input VCF, we have a complete tutorial in resolve that. 

Please refer to the tutorial [here](https://github.com/zhouhufeng/FAVORannotator/blob/main/Docs/Tutorial/Demos/preprocessVCF.md), https://github.com/zhouhufeng/FAVORannotator/blob/main/Docs/Tutorial/Demos/preprocessVCF.md

You can see the Step 3 and step 4, is the step you need to get rid of the multi-allelic sites, 

Step 3: Break the multi-allelic sites into multiple rows of all the VCFs of each study.
Script:
$ bcftools norm -m -any --threads 12 ./ConcatVCF/ukb23156_c19_c12.vcf.gz -Oz -o ./ConcatVCF/ukb23156_c19_c12.bk.vcf.gz
Input: The VCF file contains multi-allelic sites ** ukb23156_c19_c12.vcf.gz **
Output: The VCF file has multi-allelic sites break into multiple lines ** ukb23156_c19_c12.bk.vcf.gz**.
Note: multi-allelic sites cause issues for the following analysis, we usually break them into multiple rows in the preprocessing steps.

Step 4: Normalize (left) the broken multi-allelic VCFs.
Script:
$ bcftools norm -f --threads 12 hg38.p13.fa ./ConcatVCF/ukb23156_c19_c12.bk.vcf.gz -Oz -o ./ConcatVCF/ukb23156_c19_c12.bk.nm.vcf.gz
Input: The VCF file has multi-allelic sites break into multiple lines ** ukb23156_c19_c12.bk.vcf.gz**, and the reference genome fasta file hg38.p13.fa.
Output: The left-normalized VCF file has multi-allelic sites break into multiple lines ** ukb23156_c19_c12.bk.nm.vcf.gz**.
Note: left-normalization is critical for the indels to have the correct and most commonly accepted formats and representation.

**Comment by alohasiqi** [comment]
Thanks! This is very helpful. I really appreciate your help!
